CREATE DATABASE CLUB_UAN;

GO

USE CLUB_UAN;

CREATE TABLE TIPO_SUBSCRIPCION (
	ID_TIPO_SUB INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	TIPO NVARCHAR (20) NOT NULL,
	FONDO_INICIAL_MIN DECIMAL (10,2) NOT NULL,
	FONDO_MAX DECIMAL (10,2) NOT NULL,
	CHECK (TIPO IN ('VIP', 'REGULAR'))
	)

CREATE TABLE SOCIO (
	ID_SOCIO INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	NUM_DOC_SOCIO INT NOT NULL,
	NOMBRE NVARCHAR (20) NOT NULL,
	FONDOS_DISPO DECIMAL (10,2) NOT NULL,
	ID_TIPO_SUB INT NOT NULL,
	FOREIGN KEY (ID_TIPO_SUB) REFERENCES TIPO_SUBSCRIPCION(ID_TIPO_SUB)
	)

CREATE TABLE AFILIADO (
	ID_AFILIADO INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	NUMERO_DOC INT NOT NULL,
	NOMBRE NVARCHAR (50) NOT NULL,
	ID_SOCIO INT NOT NULL,
	FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO(ID_SOCIO)
	)

CREATE TABLE FACTURA (
	ID_FACTURA INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	CONCEPTO NVARCHAR (100) NOT NULL,
	VALOR DECIMAL (10,2) NOT NULL,
	CLIENTE NVARCHAR(50) NOT NULL,
	ESTADO_PAGO BIT NOT NULL,
	ID_SOCIO INT NOT NULL,
	ID_AFILIADO INT NULL,
	FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO(ID_SOCIO),
    FOREIGN KEY (ID_AFILIADO) REFERENCES AFILIADO(ID_AFILIADO)
	)