USE CLUB_UAN;

GO 

CREATE NONCLUSTERED INDEX IX_TIPO_SUBSCRIPCION_TIPO
ON TIPO_SUBSCRIPCION (TIPO);

CREATE NONCLUSTERED INDEX IX_SOCIO_NUMERO_DOC
ON SOCIO (NUM_DOC_SOCIO);

CREATE NONCLUSTERED INDEX IX_SOCIO_NOMBRE
ON SOCIO (NOMBRE);

CREATE NONCLUSTERED INDEX IX_AFILIADO_NUMERO_AFILIADO
ON AFILIADO (NUMERO_DOC);

CREATE NONCLUSTERED INDEX IX_FACTURA_ID_SOCIO
ON FACTURA (ID_SOCIO);

CREATE NONCLUSTERED INDEX IX_FACTURA_ID_AFILIADO
ON FACTURA (ID_AFILIADO);

