USE CLUB_UAN;

GO

CREATE PROCEDURE AFILIAR_SOCIO 
	@NUMERO_DOC_SOCIO INT,
	@NOMBRE_SOCIO NVARCHAR(50),
	@TIPO_SUBSCRIPCION NVARCHAR (20),
	@FONDOS_INICIALES DECIMAL(10,2)

AS	
BEGIN
	DECLARE @MIN_FONDOS DECIMAL(10,2);
    DECLARE @MAX_FONDOS DECIMAL(10,2);

	SELECT @MIN_FONDOS = FONDO_INICIAL_MIN, @MAX_FONDOS = FONDO_MAX
    FROM TIPO_SUBSCRIPCION
    WHERE TIPO = @TIPO_SUBSCRIPCION;

	IF @FONDOS_INICIALES<@MIN_FONDOS
	BEGIN
        PRINT 'EL MONTO MINIMO PARA EL REGSITRO DE UN USUARIO TIPO '+CONVERT(NVARCHAR,@TIPO_SUBSCRIPCION)+' ES '+CONVERT(NVARCHAR,@MIN_FONDOS)+' TE FALTAN: '+ CONVERT(NVARCHAR,@MIN_FONDOS-@FONDOS_INICIALES);
        RETURN; 
    END

	IF @FONDOS_INICIALES>@MAX_FONDOS
	BEGIN
        PRINT 'EL MONTO MAXIMO PARA EL REGSITRO DE UN USUARIO TIPO '+CONVERT(NVARCHAR,@TIPO_SUBSCRIPCION)+' ES '+CONVERT(NVARCHAR,@MAX_FONDOS)+' TE SOBRAN: '+ CONVERT(NVARCHAR,@FONDOS_INICIALES-@MAX_FONDOS);;
        RETURN; 
    END
	
	IF EXISTS (SELECT NUM_DOC_SOCIO DOCUMENTO FROM SOCIO WHERE NUM_DOC_SOCIO = @NUMERO_DOC_SOCIO)
    BEGIN
        PRINT 'EL NUMERO DE DOCUMENTO '+CONVERT(NVARCHAR, @NUMERO_DOC_SOCIO)+' YA EXISTE EN UN SOCIO. NO SE PUEDE AGREGAR EL SOCIO.';
        RETURN; 
    END

	IF EXISTS (SELECT NUMERO_DOC DOCUMENTO FROM AFILIADO WHERE NUMERO_DOC = @NUMERO_DOC_SOCIO)
    BEGIN
        PRINT 'EL NUMERO DE DOCUMENTO '+CONVERT(NVARCHAR, @NUMERO_DOC_SOCIO)+' YA EXISTE EN UN AFILIADO. NO SE PUEDE AGREGAR EL SOCIO.';
        RETURN; 
    END	

	IF @TIPO_SUBSCRIPCION ='VIP'
	BEGIN	
		DECLARE @TOTALVIP INT;
		SET @TOTALVIP = (
			SELECT COUNT (NUM_DOC_SOCIO)  
			FROM SOCIO S JOIN TIPO_SUBSCRIPCION TS ON TS.ID_TIPO_SUB =S.ID_TIPO_SUB
			WHERE TS.TIPO='VIP');
		IF @TOTALVIP>=3
		BEGIN
			PRINT 'YA EXISTEN 3 SOCIOS VIP POR LO CUAL NO SE PUEDEN AGREGAR MAS SOCIOS VIP';
			RETURN; 
		END
	END 

	INSERT INTO SOCIO (NUM_DOC_SOCIO, NOMBRE, FONDOS_DISPO, ID_TIPO_SUB)
	VALUES (@NUMERO_DOC_SOCIO,@NOMBRE_SOCIO,@FONDOS_INICIALES,(SELECT ID_TIPO_SUB FROM TIPO_SUBSCRIPCION WHERE TIPO=@TIPO_SUBSCRIPCION))
	PRINT 'SOCIO AGREGADO EXITOSAMENTE.';
END;