USE CLUB_UAN;

GO

CREATE PROCEDURE TIPOS_DE_INSCRIPCION
	@TIPO NVARCHAR (20),
	@FONDO_INICIAL_MIN DECIMAL (10,2),
	@FONDO_MAX DECIMAL (10,2)

AS BEGIN 

	IF (@TIPO != 'VIP' AND @TIPO != 'REGULAR')
	BEGIN
		PRINT 'EL TIPO DE SUBSCRIPCION '+@TIPO+' NO ES VALIDO';
		RETURN;
	END

	IF EXISTS (SELECT * FROM TIPO_SUBSCRIPCION WHERE TIPO = @TIPO)
	BEGIN
		PRINT 'EL TIPO DE SUBSCRIPCION '+@TIPO+' YA EXISTE';
		RETURN;
	END

	
	INSERT INTO TIPO_SUBSCRIPCION (TIPO,FONDO_INICIAL_MIN,FONDO_MAX)
	VALUES (@TIPO,@FONDO_INICIAL_MIN,@FONDO_MAX)
	PRINT 'EL TIPO DE SUBSCRIPCION '+@TIPO+' SE CREO DE FORMA EXITOSA';
END;

