USE CLUB_UAN;
GO 

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'AUMENTAR_CUPO')
    DROP PROCEDURE AUMENTAR_CUPO;
GO

CREATE PROCEDURE AUMENTAR_CUPO  
	@NUMERO_DOC_SOCIO INT,
	@CANTIDAD_A_AUMENTAR DECIMAL(10,2)

AS BEGIN 
	 DECLARE @MAX_FONDOS DECIMAL(10,2);
	 DECLARE @CUPO_DISPONIBLE DECIMAL (10,2);
	 DECLARE @FONDOS_DISPONIBLES DECIMAL(10,2);
	 DECLARE @TIPO_SUBSCRIPCION NVARCHAR (50);
	 DECLARE @SOCIO_NOMBRE NVARCHAR (50);

	 SELECT @MAX_FONDOS = TS.FONDO_MAX, @CUPO_DISPONIBLE = S.CUPO_DISPONIBLE, @FONDOS_DISPONIBLES = S.FONDOS_DISPO, @TIPO_SUBSCRIPCION = TS.TIPO,@SOCIO_NOMBRE =  S.NOMBRE
	 FROM SOCIO S JOIN TIPO_SUBSCRIPCION TS ON TS.ID_TIPO_SUB=S.ID_TIPO_SUB WHERE NUM_DOC_SOCIO=@NUMERO_DOC_SOCIO

	 IF NOT EXISTS (SELECT NUM_DOC_SOCIO DOCUMENTO FROM SOCIO WHERE NUM_DOC_SOCIO = @NUMERO_DOC_SOCIO)
		BEGIN
			PRINT 'EL NUMERO DE DOCUMENTO '+CONVERT(NVARCHAR, @NUMERO_DOC_SOCIO)+' NO EXISTE COMO SOCIO.';
			RETURN; 
		END

	 IF @CUPO_DISPONIBLE+@CANTIDAD_A_AUMENTAR > @MAX_FONDOS
	 BEGIN
		PRINT 'EL MONTO MAXIMO PARA EL UN USUARIO TIPO '+@TIPO_SUBSCRIPCION+' ES '+CONVERT(NVARCHAR,@MAX_FONDOS)+' TE SOBRAN : '+ CONVERT(NVARCHAR,@CUPO_DISPONIBLE+@CANTIDAD_A_AUMENTAR-@MAX_FONDOS);
        RETURN;
	 END


	 UPDATE SOCIO
	 SET CUPO_DISPONIBLE = @CUPO_DISPONIBLE + @CANTIDAD_A_AUMENTAR,FONDOS_DISPO = @FONDOS_DISPONIBLES + @CANTIDAD_A_AUMENTAR WHERE NUM_DOC_SOCIO = @NUMERO_DOC_SOCIO;

	 PRINT 'CUPO DISPONIBLE AUMENTADO EXITOSAMENTE.'
	 PRINT 'PARA EL SOCIO ' + @SOCIO_NOMBRE;
	 PRINT '';
	 PRINT ' SU NUEVO CUPO DISPONIBLE ES:' + CONVERT(NVARCHAR,@CUPO_DISPONIBLE+@CANTIDAD_A_AUMENTAR) ;
	 PRINT ' SU NUEVO FONDO DISPONIBLE ES:' + CONVERT(NVARCHAR,@FONDOS_DISPONIBLES+@CANTIDAD_A_AUMENTAR) ;

END; 
