USE CLUB_UAN;
GO 

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'AGREGAR_AFILIADO')
    DROP PROCEDURE AGREGAR_AFILIADO;
GO

CREATE PROCEDURE AGREGAR_AFILIADO 
	@NUMERO_DOC_SOCIO INT,
	@NUMERO_DOC_AFILIADO INT,
	@NOMBRE_AFILIADO NVARCHAR (50)


AS BEGIN 
	DECLARE @ID_SOCIO INT;
	DECLARE @FONDOS_DISPONIBLES DECIMAL(10,2);
	DECLARE @SOCIO_NOMBRE NVARCHAR (50);
	
	SELECT @ID_SOCIO = ID_SOCIO, @FONDOS_DISPONIBLES = S.FONDOS_DISPO, @SOCIO_NOMBRE =  S.NOMBRE
	FROM SOCIO S WHERE NUM_DOC_SOCIO=@NUMERO_DOC_SOCIO
	
	IF NOT EXISTS (SELECT NUM_DOC_SOCIO DOCUMENTO FROM SOCIO WHERE NUM_DOC_SOCIO = @NUMERO_DOC_SOCIO)
		BEGIN
			PRINT 'EL NUMERO DE DOCUMENTO '+CONVERT(NVARCHAR, @NUMERO_DOC_SOCIO)+' NO EXISTE COMO SOCIO.';
			RETURN; 
		END
	IF EXISTS (SELECT NUM_DOC_SOCIO DOCUMENTO FROM SOCIO WHERE NUM_DOC_SOCIO = @NUMERO_DOC_AFILIADO)
		BEGIN
			PRINT 'EL NUMERO DE DOCUMENTO '+CONVERT(NVARCHAR, @NUMERO_DOC_AFILIADO)+' EXISTE COMO SOCIO.';
			RETURN; 
		END
	IF EXISTS (SELECT NUMERO_DOC DOCUMENTO FROM AFILIADO WHERE NUMERO_DOC = @NUMERO_DOC_AFILIADO)
		BEGIN
			PRINT 'EL NUMERO DE DOCUMENTO '+CONVERT(NVARCHAR, @NUMERO_DOC_AFILIADO)+' EXISTE COMO AFILIADO.';
			RETURN; 
		END
	IF @FONDOS_DISPONIBLES = 0
		BEGIN 
			PRINT 'EL SOCIO: ' + @SOCIO_NOMBRE;
			PRINT 'CON NUMERO DE DOCUMENTO '+CONVERT(NVARCHAR, @NUMERO_DOC_AFILIADO)+' NO CUENTA CON FONDOS DISPONIBLES SUFICIENTES.';
			PRINT 'NO SE PUDO AGREGAR EL AFILIADO';
			RETURN; 
		END
	INSERT INTO AFILIADO(NUMERO_DOC,NOMBRE,ID_SOCIO)
	VALUES (@NUMERO_DOC_AFILIADO,@NOMBRE_AFILIADO,@ID_SOCIO)
	PRINT 'AFILIADO AGREGADO EXITOSAMENTE.';
END;