USE CLUB_UAN;
GO 

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'CREAR_FACTURA')
    DROP PROCEDURE CREAR_FACTURA;
GO

CREATE PROCEDURE CREAR_FACTURA 
	@NUMERO_DOC INT,
	@FECHA DATE,
	@CONCEPTO NVARCHAR (100),
	@VALOR DECIMAL (10,2)

AS BEGIN 
	DECLARE @ID_SOCIO INT;
	DECLARE @ID_AFILIADO INT;
	DECLARE @NUMERO_DOC_SOCIO INT ;
	DECLARE @FONDOS_DISPONIBLES DECIMAL(10,2);
	DECLARE @CLIENTE NVARCHAR (50);
	DECLARE @SOCIO_NOMBRE NVARCHAR (50);
	DECLARE @AFILIADO_NOMBRE NVARCHAR (50);
	DECLARE @FACTURA INT

	IF NOT EXISTS (SELECT * FROM SOCIO S LEFT JOIN AFILIADO A ON A.ID_SOCIO=S.ID_SOCIO WHERE NUM_DOC_SOCIO = @NUMERO_DOC OR A.NUMERO_DOC=@NUMERO_DOC )
		BEGIN 
			PRINT 'EL NUMERO DE DOCUMENTO '+ CONVERT(NVARCHAR , @NUMERO_DOC)+' NO EXISTE EN LA BASE DE DATOS'
			RETURN;
		END
	IF EXISTS (SELECT * FROM AFILIADO WHERE NUMERO_DOC=@NUMERO_DOC)
		BEGIN 
			SELECT @SOCIO_NOMBRE = S.NOMBRE ,@ID_SOCIO = S.ID_SOCIO,@NUMERO_DOC_SOCIO = NUM_DOC_SOCIO ,@FONDOS_DISPONIBLES = FONDOS_DISPO,@AFILIADO_NOMBRE = A.NOMBRE ,@ID_AFILIADO = ID_AFILIADO
			FROM SOCIO S JOIN AFILIADO A ON A.ID_SOCIO=S.ID_SOCIO
			WHERE A.NUMERO_DOC=@NUMERO_DOC
			SET @CLIENTE=@AFILIADO_NOMBRE 
		END 
	ELSE 
		BEGIN 
		SELECT @SOCIO_NOMBRE = S.NOMBRE ,@ID_SOCIO = S.ID_SOCIO, @NUMERO_DOC_SOCIO = NUM_DOC_SOCIO, @FONDOS_DISPONIBLES = FONDOS_DISPO
			FROM SOCIO S WHERE NUM_DOC_SOCIO=@NUMERO_DOC
			SET @CLIENTE=@SOCIO_NOMBRE
		END 
	
	IF @FONDOS_DISPONIBLES < @VALOR
		BEGIN
			PRINT 'EL SOCIO '+ @SOCIO_NOMBRE + 'NO CUENTA CON FONDOS SUFICIENTES';
			PRINT 'NO SE PUEDE GENERAR LA FACTURA';
			RETURN;
		END 

	INSERT INTO FACTURA	(FECHA,CONCEPTO,VALOR,CLIENTE,ESTADO_PAGO,ID_SOCIO,ID_AFILIADO)
	VALUES (@FECHA,@CONCEPTO,@VALOR,@CLIENTE,0,@ID_SOCIO,@ID_AFILIADO)

		SET @FACTURA = SCOPE_IDENTITY();

	UPDATE SOCIO
	SET FONDOS_DISPO = @FONDOS_DISPONIBLES-@VALOR WHERE ID_SOCIO=@ID_SOCIO
		
				
		PRINT 'SE CREO LA FACTURA No '+CONVERT (NVARCHAR,@FACTURA);
		PRINT 'LA CUAL SE ASIGNO AL SOCIO '+@SOCIO_NOMBRE+ 'CON DOCUMENTO No '+CONVERT (NVARCHAR,@NUMERO_DOC_SOCIO);
		PRINT 'DONDE EL CLIENTE '+ @CLIENTE+' GENERO UN CONSUMO POR UN VALOR DE '+ CONVERT (NVARCHAR,@VALOR);
		PRINT 'BAJO EL CONCEPTO DE '+@CONCEPTO;

END;
