USE CLUB_UAN;
GO 

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'PAGAR_FACTURA')
    DROP PROCEDURE PAGAR_FACTURA;
GO

CREATE PROCEDURE PAGAR_FACTURA 
	@NUMERO_FACTURA INT 

AS BEGIN 
	DECLARE @ID_SOCIO INT;
	DECLARE @ID_AFILIADO INT;
	DECLARE @NUMERO_DOC_SOCIO INT ;
	DECLARE @FONDOS_DISPONIBLES DECIMAL(10,2);
	DECLARE @CUPO_DISPONIBLE DECIMAL(10,2);
	DECLARE @VALOR_FACTURA DECIMAL (10,2);
	DECLARE @CLIENTE NVARCHAR (50);
	DECLARE @CONCEPTO NVARCHAR(100);
	DECLARE @SOCIO_NOMBRE NVARCHAR (50);
	
	

	IF NOT EXISTS (SELECT * FROM FACTURA WHERE ID_FACTURA=@NUMERO_FACTURA)
		BEGIN
			PRINT 'LA FACTURA No '+CONVERT(NVARCHAR,@NUMERO_FACTURA)+' NO EXISTE';
			RETURN;
		END

	IF EXISTS (SELECT * FROM FACTURA WHERE ID_FACTURA = @NUMERO_FACTURA AND ESTADO_PAGO = 1)
    BEGIN
        PRINT 'LA FACTURA No ' + CONVERT(NVARCHAR, @NUMERO_FACTURA) + ' YA ESTA EN ESTADO DE PAGA.';
        RETURN;
    END

	SELECT @SOCIO_NOMBRE = S.NOMBRE ,@ID_SOCIO = S.ID_SOCIO,@NUMERO_DOC_SOCIO = NUM_DOC_SOCIO ,@FONDOS_DISPONIBLES = FONDOS_DISPO,
			@ID_AFILIADO = F.ID_AFILIADO,@CLIENTE = F.CLIENTE,@CUPO_DISPONIBLE= S.CUPO_DISPONIBLE,@VALOR_FACTURA=F.VALOR,@CONCEPTO= F.CONCEPTO
			FROM FACTURA F INNER JOIN SOCIO S ON S.ID_SOCIO = F.ID_SOCIO 
			WHERE F.ID_FACTURA=@NUMERO_FACTURA

	IF @CUPO_DISPONIBLE < @VALOR_FACTURA
    BEGIN
        PRINT 'NO SE PUEDE REALIZAR EL PAGO DE LA FACTURA No ' + CONVERT(NVARCHAR, @NUMERO_FACTURA) + ' POR FALTA DE CUPO.';
        PRINT 'EL CUPO DISPONIBLE ES DE ' + CONVERT(NVARCHAR, @CUPO_DISPONIBLE) + ' Y EL VALOR DE LA FACTURA ES ' + CONVERT(NVARCHAR, @VALOR_FACTURA);
        RETURN;
    END

	UPDATE FACTURA
	SET ESTADO_PAGO = 1 WHERE ID_FACTURA=@NUMERO_FACTURA

	UPDATE SOCIO
	SET CUPO_DISPONIBLE = @CUPO_DISPONIBLE-@VALOR_FACTURA WHERE ID_SOCIO=@ID_SOCIO

	PRINT 'SE REALIZO EL PAGO DE LA FACTURA No '+ CONVERT(NVARCHAR,@NUMERO_FACTURA);
	PRINT 'POR UN VALOR DE '+ CONVERT(NVARCHAR,@VALOR_FACTURA);
	PRINT 'LA CUAL ESTABA CARGADA AL SOCIO '+@SOCIO_NOMBRE+' CON NUMERO DE DOCUMENTO '+ CONVERT(NVARCHAR,@NUMERO_DOC_SOCIO);
	IF @ID_AFILIADO > 0
		BEGIN
		PRINT 'POR EL AFILIADO '+@CLIENTE;
		END 
	ELSE 
		BEGIN
		PRINT 'POR EL SOCIO '+@CLIENTE;
		END
	PRINT 'POR EL CONCEPTO DE '+@CONCEPTO;
	PRINT '';
	PRINT 'EL NUEVO CUPO DISPONIBLE DEL SOCIO '+@SOCIO_NOMBRE+' CON NUMERO DE DOCUMENTO '+ CONVERT(NVARCHAR,@NUMERO_DOC_SOCIO)+' ES '+ CONVERT(NVARCHAR,@CUPO_DISPONIBLE-@VALOR_FACTURA);
	PRINT 'Y SUS FONDOS DISPONIBLES SON '+ CONVERT(NVARCHAR,@FONDOS_DISPONIBLES);

END;