USE CLUB_UAN;
GO

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'ELIMINAR_AFILIADO')
    DROP PROCEDURE ELIMINAR_AFILIADO;
GO

CREATE PROCEDURE ELIMINAR_AFILIADO
    @NUMERO_DOC_AFILIADO INT
AS
BEGIN
    
    DECLARE @FACTURAS_PENDIENTES INT;

   	SELECT @FACTURAS_PENDIENTES=COUNT(*)
    FROM FACTURA F INNER JOIN AFILIADO A ON A.ID_AFILIADO=F.ID_AFILIADO
    WHERE A.NUMERO_DOC = @NUMERO_DOC_AFILIADO AND ESTADO_PAGO = 0;

    IF @FACTURAS_PENDIENTES > 0
    BEGIN
        PRINT 'EL AFILIADO CON NÚMERO DE DOCUMENTO ' + CONVERT(NVARCHAR, @NUMERO_DOC_AFILIADO) + ' TIENE FACTURAS PENDIENTES DE PAGO Y NO PUEDE SER ELIMINADO.';
        RETURN;
    END

    DELETE FROM AFILIADO
    WHERE NUMERO_DOC = @NUMERO_DOC_AFILIADO;

    PRINT 'EL AFILIADO CON NÚMERO DE DOCUMENTO ' + CONVERT(NVARCHAR, @NUMERO_DOC_AFILIADO) + ' HA SIDO ELIMINADO EXITOSAMENTE.';
END;
