USE TALLER2GUIA3;
--PUNTO A CONSULTAR EL CODIGO DE LOS REALIZADOS POR EL JUGADOR "JUAN PEREA".
SELECT G.CODIGO_GOL 
FROM JUGADOR J INNER JOIN JUGADOR_GOL JG ON JG.CODIGO_JUGADOR=J.CODIGO_JUGADOR  
			   INNER JOIN GOL G ON G.CODIGO_GOL=JG.CODIGO_GOL 
WHERE J.NOMBRE='JUAN PEREA'
--PUNTO B CONSULTAR TODOS LOS GOLES REALIZADOS DE VISITANTES POR LOS JUGADORES DE LA POSICION DE "DEFENSAS"
SELECT G.*,P.FECHA AS FECHA_PARTIDO,J.NOMBRE,J.POSICIOIN,E.NOMBRE EQUIPO,PE.TIPO_EQUIPO
FROM GOL G  JOIN JUGADOR_GOL JG ON JG.CODIGO_GOL=G.CODIGO_GOL 
	 JOIN JUGADOR J ON J.CODIGO_JUGADOR=JG.CODIGO_JUGADOR
	 JOIN EQUIPO E ON E.CODIGO_EQUIPO=J.CODIGO_EQUIPO 
	 JOIN PARTIDO_GOL PG ON PG.CODIGO_GOL=G.CODIGO_GOL
	 JOIN PARTIDO P ON P.CODIGO_PARTIDO=PG.CODIGO_PARTIDO
	 JOIN PARTIDO_EQUIPO PE ON PE.CODIGO_PARTIDO=P.CODIGO_PARTIDO AND E.CODIGO_EQUIPO=PE.CODIGO_EQUIPO
WHERE PE.TIPO_EQUIPO='VISITANTE' AND J.POSICIOIN='DEFENSA'
--PUNTO C CONSULTAR EL PRESIDENTE DEL EQUIPO DE FUTBOL "LOS TIBURONES"
SELECT P.* 
FROM PRESIDENTE P JOIN EQUIPO E ON P.CODIGO_EQUIPO=E.CODIGO_EQUIPO 
WHERE E.NOMBRE='LOS TIBURONES'
--PUNTO D LISTAR TODA LA NOMINA DE JUGADORES DEL EQUIPO "LOS TIBURONES"
SELECT J.NOMBRE,J.NUMERO_DOC,'JUGADOR' AS CARGO, E.NOMBRE AS EQUIPO 
FROM JUGADOR J JOIN EQUIPO E ON J.CODIGO_EQUIPO=E.CODIGO_EQUIPO 
WHERE E.NOMBRE='LOS TIBURONES'
--PUNTO E CONSULTAR JUGADORES QUE NO HAN MARCADO UN GOL EN EL TORNEO
SELECT J.* 
FROM JUGADOR J FULL OUTER JOIN JUGADOR_GOL JG ON JG.CODIGO_JUGADOR=J.CODIGO_JUGADOR 
WHERE JG.CODIGO_GOL IS NULL
--PUNTO F CONSULTAR SI EXISTE UN JUGADOR QUE TAMBIEN SEA EL PRESIDENTE DEL EQUIPO DONDE MILITA 
SELECT *
FROM JUGADOR J JOIN EQUIPO E ON J.CODIGO_EQUIPO=E.CODIGO_EQUIPO 
	JOIN PRESIDENTE P ON P.CODIGO_EQUIPO=E.CODIGO_EQUIPO AND J.NUMERO_DOC=P.NUMERO_DOC 
--PUNTO G CONSULTAR LOS EQUIPOS DE FUTBOL QUE TIENEN MAS GOLES REALIZADOS ANTES DE LOS PRIMEROS 15 MINUTOS 
SELECT COUNT (E.NOMBRE )  CANTIDAD , E.NOMBRE 
FROM GOL G JOIN JUGADOR_GOL JG ON JG.CODIGO_GOL = G.CODIGO_GOL 
	JOIN JUGADOR J ON JG.CODIGO_JUGADOR=J.CODIGO_JUGADOR 
	JOIN EQUIPO E ON E.CODIGO_EQUIPO=J.CODIGO_EQUIPO
WHERE MINUTO < 15 GROUP BY E.NOMBRE

