USE CLUB_UAN;
GO 

IF EXISTS (SELECT * FROM sys.objects WHERE type = 'V' AND name = 'VISTA_FACTURAS_PENDIENTES')
    DROP VIEW VISTA_FACTURAS_PENDIENTES;

GO
CREATE VIEW VISTA_FACTURAS_PENDIENTES
AS
SELECT
    F.ID_FACTURA,
    F.FECHA,
    F.CONCEPTO,
    F.VALOR,
    F.CLIENTE,
    F.ESTADO_PAGO,
    CASE
        WHEN F.ID_AFILIADO IS NOT NULL THEN A.NUMERO_DOC
        ELSE S.NUM_DOC_SOCIO
    END AS NUMERO_DOC, 
    CASE
        WHEN F.ID_AFILIADO IS NOT NULL THEN A.NOMBRE
        ELSE S.NOMBRE
    END AS NOMBRE_CLIENTE 
FROM FACTURA F
LEFT JOIN SOCIO S ON F.ID_SOCIO = S.ID_SOCIO
LEFT JOIN AFILIADO A ON F.ID_AFILIADO = A.ID_AFILIADO
WHERE F.ESTADO_PAGO = 0; 
